name: eventful-test-helpers
version: "0.1.2"
maintainer: David Reaver
synopsis: Common module used for eventful tests
description: Common module used for eventful tests
maintainer: David Reaver
stability: experimental
category: Database,Eventsourcing
license: MIT
license-file: LICENSE.md

github: jdreaver/eventful

dependencies:
  - base >= 4.9 && < 5
  - eventful-core

  - aeson
  - aeson-casing
  - extra
  - hspec
  - monad-logger

library:
  source-dirs:
    - src
  ghc-options: -Wall
